#!/bin/sh

source ~/.rc/functions

[ $SHELL != "bash" ] && return

# History settings
export HISTCONTROL='ignoredups:ignoreboth'
export HISTSIZE=100000
# export PROMPT_COMMAND='history -a; history -r; $PROMPT_COMMAND'
export PROMPT_COMMAND='history -a; history -r'

shopt -s histappend

#export CDPATH='.:~/.:/media:/etc:/usr:/usr/local'

[ -f /etc/bash_completion ] && . /etc/bash_completion

shopt -s autocd checkjobs checkwinsize cdable_vars cdspell \
         cmdhist dirspell dotglob globstar no_empty_cmd_completion 2>/dev/null

