#!/bin/sh

sd() {
    DIR="$1"
    [ -z "$DIR" ] && DIR="$(sel)" && if [ ! -d "$DIR" ]; then DIR="$(dirname "$DIR")"; fi
    [ -d "$DIR" ] && pushd "$DIR" && ls
}

is_login_shell() {
    shopt | grep login_shell | grep -q on 
}
