#!/bin/sh

LSFLAGS="-shAF"

if [ "$(uname)" = "Darwin" ]; then
    LSFLAGS="$LSFLAGS -G"
else
    if [ "$TERM" != "dumb" ]; then
        eval "`dircolors -b`"
    fi

    LSFLAGS="-shAF --color=auto --group-directories-first --show-control-chars"
fi

alias ll="ls $LSFLAGS -l"
alias ls="ls $LSFLAGS"
alias l=ls
