#!/bin/sh

PS1='\[\033[01;34m\]\w\[\033[00m\]\$ '

# if [ "\$(type -t __git_ps1)" ]; then
#     GIT_PS1_SHOWDIRTYSTATE=1
#     GIT_PS1_SHOWSTASHSTATE=1
#     GIT_PS1_SHOWUNTRACKEDFILES=1
#     PS1="\$(__git_ps1 '(%s) ')$PS1"
# fi
 
PS1='`_ret=$?; if test $_ret -ne 0; then echo "$_ret:"; set ?=$_ret; unset _ret; fi`'"$PS1"
